import type { NormativeChunk, NormativeDocumentRef } from "@/rag/index";

export const REAL_NORMATIVE_DOCUMENTS: NormativeDocumentRef[] = [
  {
    id: "doc-lc123-simples",
    slug: "lc-123-2006-simples-nacional",
    title: "LC 123/2006 — Simples Nacional: alíquotas e faixas de receita (Anexos I a V)",
    kind: "official_text",
    status: "draft",
    jurisdiction: "federal",
    sourceLabel: "Lei Complementar nº 123, de 14 de dezembro de 2006",
    sourceUrl: "https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp123.htm",
    publishedAt: "2006-12-14",
    disclaimer: "Chunks derivados da LC 123/2006 e Resolução CGSN 140/2018. Revisão humana obrigatória antes de qualquer decisão fiscal.",
    explicitPlaceholder: false,
  },
  {
    id: "doc-mei-das-2026",
    slug: "mei-das-2026",
    title: "MEI — Microempreendedor Individual: DAS 2026 e limite de faturamento",
    kind: "official_text",
    status: "draft",
    jurisdiction: "federal",
    sourceLabel: "LC 123/2006 art. 18-A e Resolução CGSN 162/2024",
    publishedAt: "2024-01-01",
    disclaimer: "Valores do DAS MEI calculados sobre salário mínimo 2026 (R$ 1.518,00). Confirmar valores atualizados com a Receita Federal.",
    explicitPlaceholder: false,
  },
  {
    id: "doc-lucro-presumido",
    slug: "lucro-presumido-rir-2018",
    title: "Lucro Presumido — IRPJ, CSLL, PIS e COFINS (RIR/2018 e Lei 9.430/1996)",
    kind: "official_text",
    status: "draft",
    jurisdiction: "federal",
    sourceLabel: "Decreto 9.580/2018 (RIR/2018), arts. 591-597; Lei 9.718/1998",
    sourceUrl: "https://www.planalto.gov.br/ccivil_03/_ato2015-2018/2018/decreto/D9580.htm",
    publishedAt: "2018-11-22",
    disclaimer: "Estimativas de Lucro Presumido não incluem INSS patronal (depende da folha), contribuições estaduais/municipais variáveis e incentivos específicos.",
    explicitPlaceholder: false,
  },
  {
    id: "doc-fator-r",
    slug: "fator-r-simples-nacional",
    title: "Fator R — Determinação do Anexo III ou V no Simples Nacional",
    kind: "official_text",
    status: "draft",
    jurisdiction: "federal",
    sourceLabel: "Resolução CGSN 140/2018, art. 25-A",
    disclaimer: "Fator R requer folha de salários + pró-labore dos últimos 12 meses, não apenas despesas totais. Confirmar com contador.",
    explicitPlaceholder: false,
  },
  {
    id: "doc-reforma-tributaria-2026",
    slug: "reforma-tributaria-ibs-cbs-2026",
    title: "Reforma Tributária — IBS e CBS: transição 2026-2033 (EC 132/2023)",
    kind: "official_text",
    status: "draft",
    jurisdiction: "federal",
    sourceLabel: "Emenda Constitucional 132/2023 e Lei Complementar da Reforma Tributária",
    publishedAt: "2023-12-20",
    disclaimer: "Alíquotas-teste em 2026 têm impacto marginal. Regime de transição gradual até 2033. Análise de impacto requer acompanhamento legislativo contínuo.",
    explicitPlaceholder: false,
  },
  {
    id: "doc-guardrails-revisao",
    slug: "guardrails-revisao-humana",
    title: "Limitações e obrigação de revisão humana — EconomizaIA Local",
    kind: "internal_note",
    status: "review_required",
    jurisdiction: "unknown",
    sourceLabel: "Política interna de governança do EconomizaIA Local",
    disclaimer: "Documento interno. Não substitui orientação jurídica ou contábil.",
    explicitPlaceholder: true,
  },
];

export const REAL_NORMATIVE_CHUNKS: NormativeChunk[] = [
  // ── Simples Nacional ──────────────────────────────────────────────────────
  {
    id: "chunk-simples-01",
    documentId: "doc-lc123-simples",
    ordinal: 1,
    text: "O Simples Nacional é um regime tributário simplificado que unifica o recolhimento de IRPJ, CSLL, PIS, COFINS, CPP, ICMS e ISS em um único documento de arrecadação (DAS). Podem optar pelo Simples Nacional microempresas com receita bruta anual de até R$ 360.000 e empresas de pequeno porte com receita bruta anual de até R$ 4.800.000.",
    keywords: ["simples nacional", "das", "microempresa", "empresa pequeno porte", "irpj", "csll", "pis", "cofins", "icms", "iss", "4800000", "360000"],
    sectionLabel: "Conceito e elegibilidade",
    tokenEstimate: 62,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-simples-02",
    documentId: "doc-lc123-simples",
    ordinal: 2,
    text: "Anexo I — Comércio (revenda de mercadorias): alíquotas nominais de 4,00% (até R$ 180 mil/ano) a 19,00% (até R$ 4,8 mi/ano). Alíquota efetiva = (RBA × alíquota nominal − dedução) / RBA. Para R$ 180 mil/ano: 4,00% sem dedução (efetivo = 4,00%). Para R$ 360 mil/ano: 7,30% − R$ 5.940 dedução. Para R$ 720 mil/ano: 9,50% − R$ 13.860.",
    keywords: ["anexo i", "comercio", "revenda", "mercadorias", "aliquota", "4%", "efetivo", "deducao", "180000", "360000", "720000"],
    sectionLabel: "Anexo I — Comércio",
    tokenEstimate: 72,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-simples-03",
    documentId: "doc-lc123-simples",
    ordinal: 3,
    text: "Anexo III — Serviços com Fator R ≥ 28%: alíquotas de 6,00% (até R$ 180 mil/ano) a 33,00% (até R$ 4,8 mi/ano). Deduções: R$ 0 (primeira faixa), R$ 9.360, R$ 17.640, R$ 35.640, R$ 125.640, R$ 648.000. Aplica-se a serviços como agências, consultoria, tecnologia, quando a razão folha/receita é igual ou superior a 28% nos últimos 12 meses.",
    keywords: ["anexo iii", "servicos", "fator r", "28%", "6%", "consultoria", "tecnologia", "agencia", "aliquota", "deducao"],
    sectionLabel: "Anexo III — Serviços com Fator R alto",
    tokenEstimate: 76,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-simples-04",
    documentId: "doc-lc123-simples",
    ordinal: 4,
    text: "Anexo V — Serviços com Fator R < 28%: alíquotas de 15,50% (até R$ 180 mil/ano) a 30,50% (até R$ 4,8 mi/ano). Deduções: R$ 0, R$ 4.500, R$ 9.900, R$ 17.100, R$ 62.100, R$ 540.000. Aplica-se quando a razão folha de salários + pró-labore / receita bruta acumulada nos 12 meses anteriores for inferior a 28%.",
    keywords: ["anexo v", "servicos", "fator r", "15,5%", "30,5%", "aliquota", "deducao", "pro-labore", "folha", "salarios"],
    sectionLabel: "Anexo V — Serviços com Fator R baixo",
    tokenEstimate: 73,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-simples-05",
    documentId: "doc-lc123-simples",
    ordinal: 5,
    text: "Anexo II — Indústria (fabricação/transformação): alíquotas de 4,50% (até R$ 180 mil) a 30,00% (até R$ 4,8 mi/ano). Deduções crescentes de R$ 0 a R$ 720.000. Inclui ICMS e CPP. Aplica-se à industrialização, transformação de matéria-prima, confecção e manufatura.",
    keywords: ["anexo ii", "industria", "fabricacao", "transformacao", "confeccao", "manufatura", "icms", "cpp", "4,5%"],
    sectionLabel: "Anexo II — Indústria",
    tokenEstimate: 58,
    explicitPlaceholder: false,
  },

  // ── MEI ───────────────────────────────────────────────────────────────────
  {
    id: "chunk-mei-01",
    documentId: "doc-mei-das-2026",
    ordinal: 1,
    text: "O MEI (Microempreendedor Individual) é a modalidade mais simples. Em 2026, o limite anual de faturamento é R$ 81.000 (R$ 6.750/mês). O DAS MEI mensal é composto de: INSS = 5% do salário mínimo (R$ 1.518 em 2026 = R$ 75,90). Para atividades de comércio ou indústria, adiciona-se ICMS de R$ 1,00. Para serviços, adiciona-se ISS de R$ 5,00.",
    keywords: ["mei", "das", "81000", "6750", "inss", "5%", "salario minimo", "1518", "75,90", "icms", "iss", "2026", "microempreendedor"],
    sectionLabel: "DAS MEI 2026",
    tokenEstimate: 72,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-mei-02",
    documentId: "doc-mei-das-2026",
    ordinal: 2,
    text: "Vantagens do MEI: carga tributária muito baixa (DAS fixo); cobertura previdenciária (aposentadoria por invalidez e por tempo de contribuição, auxílio-doença, salário-maternidade); pode ter um empregado com salário mínimo; CNPJ próprio; acesso a crédito bancário. Restrições: máximo de 1 empregado, vedado para profissões regulamentadas em lista específica, vedado para sócio de outra empresa.",
    keywords: ["mei", "vantagem", "previdencia", "aposentadoria", "cnpj", "credito", "empregado", "restricao", "profissao regulamentada"],
    sectionLabel: "Vantagens e restrições MEI",
    tokenEstimate: 68,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-mei-03",
    documentId: "doc-mei-das-2026",
    ordinal: 3,
    text: "Comparação de carga MEI vs Simples Nacional para serviços com receita de R$ 5.000/mês: MEI paga R$ 80,90/mês (INSS R$ 75,90 + ISS R$ 5,00), carga efetiva de 1,6%. No Simples Anexo III (Fator R alto): 6% efetivo = R$ 300/mês. No Simples Anexo V (Fator R baixo): 15,5% efetivo = R$ 775/mês. Economia do MEI vs Simples III: R$ 219/mês. Economia do MEI vs Simples V: R$ 694/mês.",
    keywords: ["mei", "simples", "comparacao", "5000", "servicos", "economia", "80,90", "300", "775", "carga efetiva"],
    sectionLabel: "Comparação MEI vs Simples",
    tokenEstimate: 82,
    explicitPlaceholder: false,
  },

  // ── Fator R ───────────────────────────────────────────────────────────────
  {
    id: "chunk-fator-r-01",
    documentId: "doc-fator-r",
    ordinal: 1,
    text: "O Fator R é a razão entre a folha de salários (incluindo pró-labore do sócio) acumulada nos 12 meses anteriores e a receita bruta acumulada no mesmo período. Se Fator R ≥ 28%: aplica-se o Anexo III (alíquotas menores, a partir de 6%). Se Fator R < 28%: aplica-se o Anexo V (alíquotas maiores, a partir de 15,5%). Empresas novas usam a média dos meses disponíveis.",
    keywords: ["fator r", "folha", "salarios", "pro-labore", "28%", "anexo iii", "anexo v", "6%", "15,5%", "receita bruta", "12 meses"],
    sectionLabel: "Fator R — definição e aplicação",
    tokenEstimate: 75,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-fator-r-02",
    documentId: "doc-fator-r",
    ordinal: 2,
    text: "Exemplo de Fator R: empresa de consultoria com receita bruta de R$ 20.000/mês e folha + pró-labore de R$ 6.000/mês. Fator R = 6.000 / 20.000 = 30%. Como 30% ≥ 28%, aplica-se Anexo III. Alíquota nominal para RBA de R$ 240.000/ano: 11,20%, dedução R$ 9.360/ano. Alíquota efetiva: (240.000 × 11,2% − 9.360) / 240.000 = 7,30%. Imposto mensal ≈ R$ 1.460.",
    keywords: ["fator r", "exemplo", "consultoria", "20000", "6000", "30%", "anexo iii", "11,2%", "7,30%", "aliquota efetiva", "1460"],
    sectionLabel: "Exemplo de cálculo com Fator R",
    tokenEstimate: 78,
    explicitPlaceholder: false,
  },

  // ── Lucro Presumido ───────────────────────────────────────────────────────
  {
    id: "chunk-lp-01",
    documentId: "doc-lucro-presumido",
    ordinal: 1,
    text: "No Lucro Presumido, o IRPJ incide sobre uma fração presumida da receita: 32% para serviços em geral, 8% para comércio e indústria, 16% para transporte de cargas, 1,6% para revenda de combustíveis. Sobre a base presumida aplica-se alíquota de 15% de IRPJ, mais adicional de 10% sobre a parcela que exceder R$ 20.000/mês de lucro presumido.",
    keywords: ["lucro presumido", "irpj", "32%", "8%", "servicos", "comercio", "15%", "adicional", "10%", "20000", "base presumida"],
    sectionLabel: "IRPJ no Lucro Presumido",
    tokenEstimate: 72,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-lp-02",
    documentId: "doc-lucro-presumido",
    ordinal: 2,
    text: "CSLL no Lucro Presumido: base de 32% sobre receita de serviços (12% para comércio). Alíquota de 9% sobre a base. PIS: 0,65% sobre receita bruta (regime cumulativo). COFINS: 3% sobre receita bruta (regime cumulativo). ISS para serviços: 2% a 5% sobre receita, variando por município (estimativa modal: 3%). INSS patronal não incluso — depende da folha de salários.",
    keywords: ["csll", "9%", "pis", "0,65%", "cofins", "3%", "iss", "2%", "5%", "lucro presumido", "inss", "patronal", "municipio"],
    sectionLabel: "CSLL, PIS, COFINS e ISS no Lucro Presumido",
    tokenEstimate: 70,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-lp-03",
    documentId: "doc-lucro-presumido",
    ordinal: 3,
    text: "Exemplo Lucro Presumido para serviços com R$ 20.000/mês: base IRPJ = 32% × R$ 20.000 = R$ 6.400. IRPJ = 15% × R$ 6.400 = R$ 960 (sem adicional). CSLL = 9% × (32% × R$ 20.000) = R$ 576. PIS = 0,65% × R$ 20.000 = R$ 130. COFINS = 3% × R$ 20.000 = R$ 600. ISS = 3% × R$ 20.000 = R$ 600. Total ≈ R$ 2.866/mês. Taxa efetiva ≈ 14,3%.",
    keywords: ["lucro presumido", "exemplo", "20000", "servicos", "irpj", "960", "csll", "576", "pis", "130", "cofins", "600", "iss", "2866", "14,3%"],
    sectionLabel: "Exemplo de cálculo Lucro Presumido",
    tokenEstimate: 85,
    explicitPlaceholder: false,
  },

  // ── Reforma Tributária ────────────────────────────────────────────────────
  {
    id: "chunk-reforma-01",
    documentId: "doc-reforma-tributaria-2026",
    ordinal: 1,
    text: "A EC 132/2023 institui a Reforma Tributária no consumo, criando o IBS (Imposto sobre Bens e Serviços, gerido por estados e municípios) e a CBS (Contribuição sobre Bens e Serviços, federal), que substituirão gradualmente PIS, COFINS, ISS e ICMS entre 2026 e 2033. Em 2026 entram em vigor alíquotas-teste: 0,1% de CBS e 0,05% de IBS, com aproveitamento de crédito sobre tributos pagos no mesmo período.",
    keywords: ["reforma tributaria", "ibs", "cbs", "ec 132", "2026", "2033", "transicao", "pis", "cofins", "iss", "icms", "aliquota teste", "0,1%", "0,05%"],
    sectionLabel: "Reforma Tributária — visão geral",
    tokenEstimate: 82,
    explicitPlaceholder: false,
  },
  {
    id: "chunk-reforma-02",
    documentId: "doc-reforma-tributaria-2026",
    ordinal: 2,
    text: "Impacto em 2026 para MEI e Simples Nacional: empresas do Simples terão regime próprio de IBS/CBS, mantendo a unificação do DAS. O impacto das alíquotas-teste de 2026 é marginal — estimado em R$ 15 a R$ 75 mensais adicionais para microempresas, compensados pelo crédito do período de teste. A carga efetiva relevante começa a mudar a partir de 2027-2029 com alíquotas escalonadas.",
    keywords: ["reforma tributaria", "mei", "simples nacional", "2026", "2027", "2029", "das", "aliquota", "marginal", "credito", "microempresa"],
    sectionLabel: "Impacto 2026 no MEI e Simples",
    tokenEstimate: 76,
    explicitPlaceholder: false,
  },

  // ── Guardrails ────────────────────────────────────────────────────────────
  {
    id: "chunk-guardrail-01",
    documentId: "doc-guardrails-revisao",
    ordinal: 1,
    text: "Esta simulação é orientativa e não substitui análise de contador habilitado. A mudança de regime tributário envolve: verificação de impedimentos (débitos fiscais, CNPJ irregular), análise do histórico dos últimos 12 meses de receita e folha, cumprimento de prazos legais (opção pelo Simples: janeiro de cada ano; exclusão: até 31 de outubro para vigência no ano seguinte).",
    keywords: ["revisao", "humana", "contador", "mudanca", "regime", "impedimento", "debito", "prazo", "simples", "opcao", "janeiro", "outubro"],
    sectionLabel: "Revisão humana e prazos legais",
    tokenEstimate: 72,
    explicitPlaceholder: true,
  },
  {
    id: "chunk-guardrail-02",
    documentId: "doc-guardrails-revisao",
    ordinal: 2,
    text: "Limites desta análise: o Fator R é estimado usando despesas declaradas como proxy de folha de salários — não é o cálculo oficial. CNAE não verificado automaticamente: algumas atividades são vedadas ao Simples ou ao MEI. INSS patronal não está incluído nas estimativas de Lucro Presumido. ISS varia por município (2% a 5%): a estimativa usa 3% como valor modal.",
    keywords: ["limite", "analise", "fator r", "estimativa", "cnae", "inss", "patronal", "iss", "municipio", "2%", "5%", "3%", "proxy", "folha"],
    sectionLabel: "Limitações e premissas",
    tokenEstimate: 68,
    explicitPlaceholder: true,
  },
];
